const center_x = 117.3;
const center_y = 172.8;
const scale_x = 0.02072;
const scale_y = 0.0205;

CUSTOM_CRS = L.extend({}, L.CRS.Simple, {
    projection: L.Projection.LonLat,
    scale: function(zoom) {

        return Math.pow(2, zoom);
    },
    zoom: function(sc) {

        return Math.log(sc) / 0.6931471805599453;
    },
	distance: function(pos1, pos2) {
        var x_difference = pos2.lng - pos1.lng;
        var y_difference = pos2.lat - pos1.lat;
        return Math.sqrt(x_difference * x_difference + y_difference * y_difference);
    },
	transformation: new L.Transformation(scale_x, center_x, -scale_y, center_y),
    infinite: true
});

var SateliteStyle = L.tileLayer('mapStyles/styleSatelite/{z}/{x}/{y}.jpg', {minZoom: 0,maxZoom: 8,noWrap: true,continuousWorld: false,attribution: 'Adelaure map GRewind',id: 'SateliteStyle map',}),
	AtlasStyle	= L.tileLayer('mapStyles/styleAtlas/{z}/{x}/{y}.jpg', {minZoom: 0,maxZoom: 5,noWrap: true,continuousWorld: false,attribution: 'Adelaure map GRewind',id: 'styleAtlas map',});
	// GridStyle	= L.tileLayer('mapStyles/styleGrid/{z}/{x}/{y}.png', {minZoom: 0,maxZoom: 5,noWrap: true,continuousWorld: false,attribution: 'Adelaure map GRewind',id: 'styleGrid map',});

var PosGroup = L.layerGroup();
var Vinewood = L.layerGroup();
var SudLS = L.layerGroup();
var SudOuestLS = L.layerGroup();
var CentreVille = L.layerGroup();
var QuartierLS = L.layerGroup();
var MarinaPlage = L.layerGroup();
var MirrorPark = L.layerGroup();
var DelPerroVespucci = L.layerGroup();
var Univ = L.layerGroup();
var Nord = L.layerGroup();



var Icons = {
	"All 10-20" :PosGroup,
    "Vinewood" :Vinewood,
    "Sud LS" :SudLS,
    "Sud Ouest LS" :SudOuestLS,
    "Centre Ville" : CentreVille,
    "Quartier LS" :QuartierLS,
    "Marina / Plage" :MarinaPlage,
    "Mirror Park" :MirrorPark,
    "Bellevue / Del Perro / Vespucci" :DelPerroVespucci,
    "Université" : Univ,
    "Nord" : Nord,

};

var mymap = L.map('map', {
    crs: CUSTOM_CRS,
    minZoom: 1,
    maxZoom: 5,
    Zoom: 5,
    maxNativeZoom: 5,
    preferCanvas: true,
    layers: [SateliteStyle],
    center: [0, 0],
    zoom: 3,
});

var layersControl = L.control.layers({ "Satelite": SateliteStyle,"Atlas": AtlasStyle}, Icons).addTo(mymap);
// var layersControl = L.control.layers({ "Satelite": SateliteStyle,"Atlas": AtlasStyle,"Grid":GridStyle}, Icons).addTo(mymap);


function customIcon(icon){
	return L.icon({
		iconUrl: `blips/${icon}.png`,
		iconSize:     [20, 20],
		iconAnchor:   [20, 20], 
		popupAnchor:  [-10, -27]
	});
}

var X  = 0;
var Y = 0;

//L.marker([haut bas,gauche droite], {icon: customIcon(1)}).addTo(Icons["All 10-20"]).bindPopup("Description");
//'<div style="text-align:center;"><h3>Lieu</h3><a href="../img/nom-img.png" target="_blank"><img src="../img/nom-img.png" alt="Lieu" style="width:300px;height:auto;border-radius:8px;"></a></div>'

//Secteur Vinewood
L.marker([1575,-415], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Boule Orange</h3><a href="https://imgur.com/xCHivak.jpg" target="_blank"><img src="https://imgur.com/xCHivak.jpg" alt="Boule Orange" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1125,-400], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Observatoire</h3><a href="https://imgur.com/o8oowCa.jpg" target="_blank"><img src="https://imgur.com/o8oowCa.jpg" alt="Observatoire" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([860,-800], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Parc à chiens</h3><a href="https://imgur.com/SXSxy4f.jpg" target="_blank"><img src="https://imgur.com/SXSxy4f.jpg" alt="Parc à chiens" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([880,-80], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Villas Lac / La Goutte</h3><a href="https://imgur.com/TCK9LgS.jpg" target="_blank"><img src="https://imgur.com/TCK9LgS.jpg" alt="Villas Lac" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1175,230], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Sisyphus</h3><a href="https://imgur.com/3TJfIpp.jpg" target="_blank"><img src="https://imgur.com/3TJfIpp.jpg" alt="Sisyphus" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/sWMiWc5.jpg" target="_blank"><img src="https://imgur.com/sWMiWc5.jpg" alt="Sisyphus" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1200,675], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Lettres Vinewood</h3><a href="https://imgur.com/uTdQ8fD.jpg" target="_blank"><img src="https://imgur.com/uTdQ8fD.jpg" alt="Lettres Vinewood" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([1100,1400], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Fuente Blanca</h3><a href="https://imgur.com/P8noABm.jpg" target="_blank"><img src="https://imgur.com/P8noABm.jpg" alt="Fuente Blanca" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([800,1550], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Pipeline</h3><a href="https://imgur.com/xcpav4d.jpg" target="_blank"><img src="https://imgur.com/xcpav4d.jpg" alt="Pipeline" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([600,700], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Vinewood Bowl</h3><a href="https://imgur.com/bnzzSL0.jpg" target="_blank"><img src="https://imgur.com/bnzzSL0.jpg" alt="Vinewood Bowl" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/WeJHtAQ.jpg" target="_blank"><img src="https://imgur.com/WeJHtAQ.jpg" alt="Vinewood Bowl" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([320,-755], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Eclipse Tower</h3><a href="https://imgur.com/Qej2ULs.jpg" target="_blank"><img src="https://imgur.com/Qej2ULs.jpg" alt="Eclipse Tower" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([340,-35], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Chateau DAmour</h3><a href="https://imgur.com/JFjl2xf.jpg" target="_blank"><img src="https://imgur.com/JFjl2xf.jpg" alt="Manoir Blanc" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([200,75], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Alien</h3><a href="https://imgur.com/WVgLxyq.jpg" target="_blank"><img src="https://imgur.com/WVgLxyq.jpg" alt="Alien" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([330,360], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>LTD Vinewood</h3><a href="https://imgur.com/MdQyncp.jpg" target="_blank"><img src="https://imgur.com/MdQyncp.jpg" alt="LTD Vinewood" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([260,650], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Station Essence VW</h3><a href="https://imgur.com/WxRcExL.jpg" target="_blank"><img src="https://imgur.com/WxRcExL.jpg" alt="Station Essence VW" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([170,355], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Cinema</h3><a href="https://imgur.com/wNHu7yR.jpg" target="_blank"><img src="https://imgur.com/wNHu7yR.jpg" alt="Cinema" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-20,600], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>PDP Vinewood</h3><a href="https://imgur.com/3LRO036.jpg" target="_blank"><img src="https://imgur.com/3LRO036.jpg" alt="PDP Vinewood" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([80,320], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Parking Jaune</h3><a href="https://imgur.com/gYOWvh3.jpg" target="_blank"><img src="https://imgur.com/gYOWvh3.jpg" alt="Parking Jaune" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-355,405], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Mexico</h3><a href="https://imgur.com/Jx1dDEV.jpg" target="_blank"><img src="https://imgur.com/Jx1dDEV.jpg" alt="Mexico" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-300,330], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Fleeca Mexico</h3><a href="https://imgur.com/Hg4gmQC.jpg" target="_blank"><img src="https://imgur.com/Hg4gmQC.jpg" alt="Fleeca Mexico" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([290,160], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Marylin Monroe</h3><a href="https://imgur.com/17pXCO1.jpg" target="_blank"><img src="https://imgur.com/17pXCO1.jpg" alt="Marylin Monroe" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-400,100], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Medical Center</h3><a href="https://imgur.com/lCL5J4Y.jpg" target="_blank"><img src="https://imgur.com/lCL5J4Y.jpg" alt="Chantier Alta Street" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-250,-175], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Rockford Plaza</h3><a href="https://imgur.com/v3Hwhbz.jpg" target="_blank"><img src="https://imgur.com/v3Hwhbz.jpg" alt="Rockford Plaza" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/Qiqtx1b.jpg" target="_blank"><img src="https://imgur.com/Qiqtx1b.jpg" alt="Rockford Plaza" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-200,-525], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Ancien Gouv</h3><a href="https://imgur.com/9YSwMOY.jpg" target="_blank"><img src="https://imgur.com/9YSwMOY.jpg" alt="Ancien Gouv" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-140,-350], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>LS Custom</h3><a href="https://imgur.com/yotIIYH.jpg" target="_blank"><img src="https://imgur.com/yotIIYH.jpg" alt="LS Custom" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([60,-670], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Epsilon</h3><a href="https://imgur.com/WIeuKI5.jpg" target="_blank"><img src="https://imgur.com/WIeuKI5.jpg" alt="Epsilon" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([280,-550], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Tequilala</h3><a href="https://imgur.com/diuZtTq.jpg" target="_blank"><img src="https://imgur.com/diuZtTq.jpg" alt="Tequilala" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([65,-55], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Benefactor</h3><a href="https://imgur.com/fDXMkJu.jpg" target="_blank"><img src="https://imgur.com/fDXMkJu.jpg" alt="Benefactor" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-20,-750], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Église Rockford</h3><a href="https://imgur.com/TGrmSAu.jpg" target="_blank"><img src="https://imgur.com/TGrmSAu.jpg" alt="Église Rockford" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([215,270], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Pacific Bank</h3><a href="https://imgur.com/ll5iSoN.jpg" target="_blank"><img src="https://imgur.com/ll5iSoN.jpg" alt="Pacific Bank" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([90,80], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Go Postal</h3><a href="https://imgur.com/otbkjvU.jpg" target="_blank"><img src="https://imgur.com/otbkjvU.jpg" alt="Go Postal" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([290,-145], {icon: customIcon("orange")}).addTo(PosGroup).addTo(Vinewood).bindPopup('<div style="text-align:center;"><h3>Dragon Kai</h3><a href="https://imgur.com/PZhMwhJ.jpg" target="_blank"><img src="https://imgur.com/PZhMwhJ.jpg" alt="Dragon Kai" style="width:300px;height:auto;border-radius:8px;"></a></div>');

//Sud Los Santos
L.marker([-2100,950], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Wardog</h3><a href="https://imgur.com/2GLA0NB.jpg" target="_blank"><img src="https://imgur.com/2GLA0NB.jpg" alt="Wardog" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2350,-385], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Pont Vert</h3><a href="https://imgur.com/xCBTd5D.jpg" target="_blank"><img src="https://imgur.com/xCBTd5D.jpg" alt="Pont Vert" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2650,800], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Pont Rouge</h3><a href="https://imgur.com/fE6dVNH.jpg" target="_blank"><img src="https://imgur.com/fE6dVNH.jpg" alt="Pont Rouge" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2340,370], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Pont Rancho / Pont Vagos</h3><a href="https://imgur.com/0SJeC7T.jpg" target="_blank"><img src="https://imgur.com/0SJeC7T.jpg" alt="Pont Rancho / Pont Vagos" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2600,-150], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Chantier Naval</h3><a href="https://imgur.com/yj1WzlA.jpg" target="_blank"><img src="https://imgur.com/yj1WzlA.jpg" alt="Chantier Naval" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/HJTcj9o.jpg" target="_blank"><img src="https://imgur.com/HJTcj9o.jpg" alt="Chantier Naval" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-3157,154], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Bugstars</h3><a href="https://imgur.com/wGiD4uz.jpg" target="_blank"><img src="https://imgur.com/wGiD4uz.jpg" alt="Bugstars" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-3100,550], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>MerryWeather</h3><a href="https://imgur.com/9wC58ON.jpg" target="_blank"><img src="https://imgur.com/9wC58ON.jpg" alt="MerryWeather" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2850,-450], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Post OP</h3><a href="https://imgur.com/jODJje7.jpg" target="_blank"><img src="https://imgur.com/jODJje7.jpg" alt="Post OP" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1950,1600], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Champ de Petrole</h3><a href="https://imgur.com/22kJi3D.jpg" target="_blank"><img src="https://imgur.com/22kJi3D.jpg" alt="Pétrole" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1640,1750], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Erebos Commodities</h3><a href="https://imgur.com/t6kUFNh.jpg" target="_blank"><img src="https://imgur.com/t6kUFNh.jpg" alt="Pétrole" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2525,900], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Cypress</h3><a href="https://imgur.com/X8nlIWH.jpg" target="_blank"><img src="https://imgur.com/X8nlIWH.jpg" alt="Cypress" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2150,825], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Ammunation Wardog</h3><a href="https://imgur.com/JangrDC.jpg" target="_blank"><img src="https://imgur.com/JangrDC.jpg" alt="Ammunation Wardog" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2000,1070], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Fonderie</h3><a href="https://imgur.com/o1YL0np.jpg" target="_blank"><img src="https://imgur.com/o1YL0np.jpg" alt="Fonderie" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2130,975], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Abattoir / Boucherie / Raven</h3><a href="https://imgur.com/nhT3BBl.jpg" target="_blank"><img src="https://imgur.com/nhT3BBl.jpg" alt="Abattoir / Boucherie / Raven" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2475,1070], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Casse Bus</h3><a href="https://imgur.com/6Oz7IST.jpg" target="_blank"><img src="https://imgur.com/6Oz7IST.jpg" alt="Casse Bus" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-3310,1222], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Entrepôt Terminal</h3><a href="https://imgur.com/6sIpf0v.jpg" target="_blank"><img src="https://imgur.com/6sIpf0v.jpg" alt="Amazon" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2378,864], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Midnight Club</h3><a href="https://imgur.com/0stXFL8.jpg" target="_blank"><img src="https://imgur.com/0stXFL8.jpg" alt="Terminal Zone" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-3140,1000], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Terminal</h3><a href="https://imgur.com/WGAa33f.jpg" target="_blank"><img src="https://imgur.com/WGAa33f.jpg" alt="Terminal Zone" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-3030,830], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Filou Cup</h3><a href="https://imgur.com/BfJWSIu.jpg" target="_blank"><img src="https://imgur.com/BfJWSIu.jpg" alt="Terminal Zone" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2240,-100], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Amigaz</h3><a href="https://imgur.com/KLZnHx4.jpg" target="_blank"><img src="https://imgur.com/KLZnHx4.jpg" alt="Amigaz" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-3223,214], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Club 77</h3><a href="https://imgur.com/KdI00Xr.jpg" target="_blank"><img src="https://imgur.com/KdI00Xr.jpg" alt="Terminal Zone" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-3044,152], {icon: customIcon("rouge")}).addTo(PosGroup).addTo(SudLS).bindPopup('<div style="text-align:center;"><h3>Winston Repair</h3><a href="https://imgur.com/OwNDwTe.jpg" target="_blank"><img src="https://imgur.com/OwNDwTe.jpg" alt="Wardog" style="width:300px;height:auto;border-radius:8px;"></a></div>');


//Sud Ouest LS
L.marker([-2025,-1100], {icon: customIcon("jaune")}).addTo(PosGroup).addTo(SudOuestLS).bindPopup('<div style="text-align:center;"><h3>LS Custom Sud / LS Custom Aeroport</h3><a href="https://imgur.com/Eq5LusL.jpg" target="_blank"><img src="https://imgur.com/Eq5LusL.jpg" alt="LS Custom Sud / LS Custom Aeroport" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1750,-525], {icon: customIcon("jaune")}).addTo(PosGroup).addTo(SudOuestLS).bindPopup('<div style="text-align:center;"><h3>Casse</h3><a href="https://imgur.com/g3hZ6kj.jpg" target="_blank"><img src="https://imgur.com/g3hZ6kj.jpg" alt="Casse" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2000,-250], {icon: customIcon("jaune")}).addTo(PosGroup).addTo(SudOuestLS).bindPopup('<div style="text-align:center;"><h3>Maze Bank Arena</h3><a href="https://imgur.com/61KgmpE.jpg" target="_blank"><img src="https://imgur.com/61KgmpE.jpg" alt="Maze Bank Arena" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2700,-975], {icon: customIcon("jaune")}).addTo(PosGroup).addTo(SudOuestLS).bindPopup('<div style="text-align:center;"><h3>Aéroport</h3><a href="https://imgur.com/Zgaqauz.jpg" target="_blank"><img src="https://imgur.com/Zgaqauz.jpg" alt="Aéroport" style="width:300px;height:auto;border-radius:8px;"></a></div>');


//Secteur Centre Ville
L.marker([-600,345], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Pillbox</h3><a href="https://imgur.com/QyQLeK4.jpg" target="_blank"><img src="https://imgur.com/QyQLeK4.jpg" alt="Pillbox Haut" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-750,155], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>FIB</h3><a href="https://imgur.com/7wufKmY.jpg" target="_blank"><img src="https://imgur.com/7wufKmY.jpg" alt="FIB" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-700,-10], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Gruppe6 / Union Depository</h3><a href="https://imgur.com/XRHXyvV.jpg" target="_blank"><img src="https://imgur.com/XRHXyvV.jpg" alt="Gruppe6 / Union Depository" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/h79P0XD.jpg" target="_blank"><img src="https://imgur.com/h79P0XD.jpg" alt="Gruppe6 / Union Depository" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-620,-140], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Cerberus</h3><a href="https://imgur.com/0tKvbMj.jpg" target="_blank"><img src="https://imgur.com/0tKvbMj.jpg" alt="Cerberus" style="width:300px;height:auto;border-radius:8px;"></a><h3>Parking Cerberus</h3><a href="https://imgur.com/f1uUd4z" target="_blank"><img src="https://imgur.com/f1uUd4z.jpg" alt="Parking Cerberus" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/qi1f0oE.jpg" target="_blank"><img src="https://imgur.com/qi1f0oE.jpg" alt="Parking Cerberus" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-640,-265], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Globe</h3><a href="https://imgur.com/cmCEwVO.jpg" target="_blank"><img src="https://imgur.com/cmCEwVO.jpg" alt="Globe" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-780,-300], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Parking Rouge</h3><a href="https://imgur.com/2vvuxWz.jpg" target="_blank"><img src="https://imgur.com/2vvuxWz.jpg" alt="Parking Rouge" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/pGgMjOK.jpg" target="_blank"><img src="https://imgur.com/pGgMjOK.jpg" alt="Parking Rouge" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-780,-440], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Parking Blanc</h3><a href="https://imgur.com/8q5pyHg.jpg" target="_blank"><img src="https://imgur.com/8q5pyHg.jpg" alt="Parking Blanc" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-620,-520], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Musée</h3><a href="https://imgur.com/IvD3cxU.jpg" target="_blank"><img src="https://imgur.com/IvD3cxU.jpg" alt="Musée" style="width:300px;height:auto;border-radius:8px;"></a><h3>Tunnel Musée</h3><a href="https://imgur.com/jhLBj7Z.jpg" target="_blank"><img src="https://imgur.com/jhLBj7Z.jpg" alt="Tunnel Musée" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-765,-670], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Parking Rose</h3><a href="https://imgur.com/RRDoszv.jpg" target="_blank"><img src="https://imgur.com/RRDoszv.jpg" alt="Parking Rose" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-692,-827], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Triad Records</h3><a href="https://imgur.com/Brcu5O5.jpg" target="_blank"><img src="https://imgur.com/Brcu5O5.jpg" alt="Cathédrale" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-725,-760], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Cathédrale</h3><a href="https://imgur.com/b0iO4AF.jpg" target="_blank"><img src="https://imgur.com/b0iO4AF.jpg" alt="Cathédrale" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-950,-700], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>LTD Lotus Quarter</h3><a href="https://imgur.com/jfGH75G.jpg" target="_blank"><img src="https://imgur.com/jfGH75G.jpg" alt="LTD Little Seoul" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-940,-555], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Weazel News / Weazel</h3><a href="https://imgur.com/n8bpS2y.jpg" target="_blank"><img src="https://imgur.com/n8bpS2y.jpg" alt="Weazel News / Weazel" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-980,-460], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Chantier Weazel</h3><a href="https://imgur.com/Cqjfuyw.jpg" target="_blank"><img src="https://imgur.com/Cqjfuyw.jpg" alt="Chantier Weazel" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-940,-310], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Parking Go Postal</h3><a href="https://imgur.com/d8lPBVq.jpg" target="_blank"><img src="https://imgur.com/d8lPBVq.jpg" alt="Parking Pole Emploi" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-840,-60], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Tour Maze Bank</h3><a href="https://imgur.com/rj4ZICt.jpg" target="_blank"><img src="https://imgur.com/rj4ZICt.jpg" alt="Tour Maze Bank" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1120,-30], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Concess</h3><a href="https://imgur.com/5HR9smU.jpg" target="_blank"><img src="https://imgur.com/5HR9smU.jpg" alt="Ancien Concess" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1040,-120], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>ATELIS Biotech Industries</h3><a href="https://imgur.com/I87mM9d.jpg" target="_blank"><img src="https://imgur.com/I87mM9d.jpg" alt="Chantier Concess" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1090,150], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Caesar</h3><a href="https://imgur.com/vE2ihCN.jpg" target="_blank"><img src="https://imgur.com/vE2ihCN.jpg" alt="Caesar" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-880,60], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Parking Predator/MCD</h3><a href="https://imgur.com/xZCrQrQ.jpg" target="_blank"><img src="https://imgur.com/xZCrQrQ.jpg" alt="Ancien Parking MCD" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-940,215], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Mission Row Park</h3><a href="https://imgur.com/OOaLkb7.jpg" target="_blank"><img src="https://imgur.com/OOaLkb7.jpg" alt="Places des cubes" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1110,470], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Parking Briques</h3><a href="https://imgur.com/3Fl9GhU.jpg" target="_blank"><img src="https://imgur.com/3Fl9GhU.jpg" alt="Parking Briques" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1010,470], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>PDP Mission Row</h3><a href="https://imgur.com/AP0SZqa.jpg" target="_blank"><img src="https://imgur.com/AP0SZqa.jpg" alt="PDP Mission Row" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-770,472], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Chinatown</h3><a href="https://imgur.com/8f3xPB6.jpg" target="_blank"><img src="https://imgur.com/8f3xPB6.jpg" alt="Chinatown" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-640,450], {icon: customIcon("rose")}).addTo(PosGroup).addTo(CentreVille).bindPopup('<div style="text-align:center;"><h3>Entrepôt de Bus</h3><a href="https://imgur.com/dt7XvNu.jpg" target="_blank"><img src="https://imgur.com/dt7XvNu.jpg" alt="Entrepôt de Bus" style="width:300px;height:auto;border-radius:8px;"></a></div>');

//Quartier LS
L.marker([-1345,-200], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Bennys</h3><a href="https://imgur.com/Upg3PNe.jpg" target="_blank"><img src="https://imgur.com/Upg3PNe.jpg" alt="Bennys" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1290,-74], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>LuXXX Club</h3><a href="https://imgur.com/gSRnBqf.jpg" target="_blank"><img src="https://imgur.com/gSRnBqf.jpg" alt="Bennys" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1560,-85], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Forum Drive / Chamberlain</h3><a href="https://imgur.com/U7kfFI5.jpg" target="_blank"><img src="https://imgur.com/U7kfFI5.jpg" alt="Forum Drive / Chamberlain" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1960,120], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Groove Street / Raquette</h3><a href="https://imgur.com/sbq2MVK.jpg" target="_blank"><img src="https://imgur.com/sbq2MVK.jpg" alt="Groove Street / Raquette" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1770,60], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Mega Mall</h3><a href="https://imgur.com/8zInepV.jpg" target="_blank"><img src="https://imgur.com/8zInepV.jpg" alt="Mega Mall" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1575,190], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Météorite</h3><a href="https://imgur.com/zSlScEQ.jpg" target="_blank"><img src="https://imgur.com/zSlScEQ.jpg" alt="Météorite" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1620,260], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Librairie</h3><a href="https://imgur.com/a8kNtg9.jpg" target="_blank"><img src="https://imgur.com/a8kNtg9.jpg" alt="Librairie" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1700,380], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Parking Davis</h3><a href="https://imgur.com/BAXYqRj.jpg" target="_blank"><img src="https://imgur.com/BAXYqRj.jpg" alt="Parking Davis" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1845,480], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Rancho Nord</h3><a href="https://imgur.com/pd32B26.jpg" target="_blank"><img src="https://imgur.com/pd32B26.jpg" alt="Rancho Nord" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2030,310], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Rancho Sud</h3><a href="https://imgur.com/TmyUpcl.jpg" target="_blank"><img src="https://imgur.com/TmyUpcl.jpg" alt="Rancho Sud" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1730,150], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Coiffeur Davis</h3><a href="https://imgur.com/3bcZut0.jpg" target="_blank"><img src="https://imgur.com/3bcZut0.jpg" alt="Coiffeur Davis" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1325,160], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Unicorn</h3><a href="https://imgur.com/wqTLMI7.jpg" target="_blank"><img src="https://imgur.com/wqTLMI7.jpg" alt="Unicorn" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1395,260], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Morgue</h3><a href="https://imgur.com/7dq3OHY.jpg" target="_blank"><img src="https://imgur.com/7dq3OHY.jpg" alt="Morgue" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1450,350], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Medical Center</h3><a href="https://imgur.com/Acpimws.jpg" target="_blank"><img src="https://imgur.com/Acpimws.jpg" alt="Medical Center" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1350,810], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>La Mesa</h3><a href="https://imgur.com/tIlDZxe.jpg" target="_blank"><img src="https://imgur.com/tIlDZxe.jpg" alt="La Mesa" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1550,1170], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Saint Fiacre</h3><a href="https://imgur.com/6EQT6Zq.jpg" target="_blank"><img src="https://imgur.com/6EQT6Zq.jpg" alt="Saint Fiacre" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1630,1345], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>El Burro</h3><a href="https://imgur.com/L3GsdLo.jpg" target="_blank"><img src="https://imgur.com/L3GsdLo.jpg" alt="El Burro" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1663,1320], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Voskan Tattoo</h3><a href="https://imgur.com/guLhDbe.jpg" target="_blank"><img src="https://imgur.com/guLhDbe.jpg" alt="El Burro" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1645,960], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Fridgit</h3><a href="https://imgur.com/LmOiqSF.jpg" target="_blank"><img src="https://imgur.com/LmOiqSF.jpg" alt="Fridgit" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/oFjTFAQ.jpg" target="_blank"><img src="https://imgur.com/oFjTFAQ.jpg" alt="Fridgit" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1780,750], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>SSX</h3><a href="https://imgur.com/MXK4APg.jpg" target="_blank"><img src="https://imgur.com/MXK4APg.jpg" alt="SSX" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1630,700], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Y</h3><a href="https://imgur.com/MITEX6S.jpg" target="_blank"><img src="https://imgur.com/MITEX6S.jpg" alt="Y" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1540,465], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Quartier Ukrainien</h3><a href="https://imgur.com/qGkdvZC.jpg" target="_blank"><img src="https://imgur.com/qGkdvZC.jpg" alt="Quartier Ukrainien" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1230,-50], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Quartier SDF</h3><a href="https://imgur.com/MfMBiWZ.jpg" target="_blank"><img src="https://imgur.com/MfMBiWZ.jpg" alt="Quartier SDF" style="width:300px;height:auto;border-radius:8px;"></a><a href="https://imgur.com/uZ6f9DL.jpg" target="_blank"><img src="https://imgur.com/uZ6f9DL.jpg" alt="Quartier SDF" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1350,432], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Parking Vert</h3><a href="https://imgur.com/qj9jkGm.jpg" target="_blank"><img src="https://imgur.com/qj9jkGm.jpg" alt="Parking Vert" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-2235,150], {icon: customIcon("lime")}).addTo(PosGroup).addTo(QuartierLS).bindPopup('<div style="text-align:center;"><h3>Torture Vagos</h3><a href="https://imgur.com/OzmM5OX.jpg" target="_blank"><img src="https://imgur.com/OzmM5OX.jpg" alt="Torture Vagos" style="width:300px;height:auto;border-radius:8px;"></a></div>');


//Secteur Marina/Plage
L.marker([-1300,-1300], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Magasin Masque</h3><a href="https://imgur.com/sHkyZ0A.jpg" target="_blank"><img src="https://imgur.com/sHkyZ0A.jpg" alt="Magasin Masque" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1650,-1150], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Tennis Plage</h3><a href="https://imgur.com/Nomes7Z.jpg" target="_blank"><img src="https://imgur.com/Nomes7Z.jpg" alt="Tennis Plage" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1310,-1000], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Requin</h3><a href="https://imgur.com/Dw4E7k2.jpg" target="_blank"><img src="https://imgur.com/Dw4E7k2.jpg" alt="Requin" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1325,-775], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Marina</h3><a href="https://imgur.com/Ted6Fde.jpg" target="_blank"><img src="https://imgur.com/Ted6Fde.jpg" alt="Marina" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1450,-700], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Heliport Marina</h3><a href="https://imgur.com/OWpKtKZ.jpg" target="_blank"><img src="https://imgur.com/OWpKtKZ.jpg" alt="Heliport Marina" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1250,-615], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Restaurant Chinois</h3><a href="https://imgur.com/UZ7GWkC.jpg" target="_blank"><img src="https://imgur.com/UZ7GWkC.jpg" alt="Restaurant Chinois" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1465,-450], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Flamme Olympique</h3><a href="https://imgur.com/EiVBX2Z.jpg" target="_blank"><img src="https://imgur.com/EiVBX2Z.jpg" alt="Flamme Olympique" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1110,-800], {icon: customIcon("azur")}).addTo(PosGroup).addTo(MarinaPlage).bindPopup('<div style="text-align:center;"><h3>Binco Little Seoul</h3><a href="https://imgur.com/d1DDaQA.jpg" target="_blank"><img src="https://imgur.com/d1DDaQA.jpg" alt="Binco Little Seoul" style="width:300px;height:auto;border-radius:8px;"></a></div>');

//Secteur Mirror Park
L.marker([-575,1125], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Mirror Park</h3><a href="https://imgur.com/toIehYc.jpg" target="_blank"><img src="https://imgur.com/toIehYc.jpg" alt="Mirror Park" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-830,760], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Arcade</h3><a href="https://imgur.com/4fiRF95.jpg" target="_blank"><img src="https://imgur.com/4fiRF95.jpg" alt="Arcade" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-755,803], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Luchettis</h3><a href="https://imgur.com/.jpg" target="_blank"><img src="https://imgur.com/.jpg" alt="Luchettis" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-175,910], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Taxi</h3><a href="https://imgur.com/7BOujIO.jpg" target="_blank"><img src="https://imgur.com/7BOujIO.jpg" alt="taxi" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-25,1675], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Barrage</h3><a href="https://imgur.com/Fczp2vw.jpg" target="_blank"><img src="https://imgur.com/Fczp2vw.jpg" alt="Barrage" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([25,975], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Casino</h3><a href="https://imgur.com/UfzNJ21.jpg" target="_blank"><img src="https://imgur.com/UfzNJ21.jpg" alt="Casino" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-400,2500], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Noose</h3><a href="https://imgur.com/wFIBtOP.jpg" target="_blank"><img src="https://imgur.com/wFIBtOP.jpg" alt="Noose" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-725,2800], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Plage El Burro / Alcatraz</h3><a href="https://imgur.com/Nz2SJ4O.jpg" target="_blank"><img src="https://imgur.com/Nz2SJ4O.jpg" alt="Plage Alcatraz" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([375,2575], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>LTD Palomino</h3><a href="https://imgur.com/HQJbd4A.jpg" target="_blank"><img src="https://imgur.com/HQJbd4A.jpg" alt="LTD Palomino" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1100,760], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>LS Custom La Mesa</h3><a href="https://imgur.com/5DX9lHj.jpg" target="_blank"><img src="https://imgur.com/5DX9lHj.jpg" alt="LS Custom La Mesa" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-922,888], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Apex Nightclub</h3><a href="https://imgur.com/.jpg" target="_blank"><img src="https://imgur.com/.jpg" alt="Apex Nightclub" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-985,955], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Maibatsu Motors</h3><a href="https://imgur.com/rMyu1N2.jpg" target="_blank"><img src="https://imgur.com/rMyu1N2.jpg" alt="Maibatsu Motors" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([100,1150], {icon: customIcon("bleu")}).addTo(PosGroup).addTo(MirrorPark).bindPopup('<div style="text-align:center;"><h3>Hippodrome</h3><a href="https://imgur.com/dK3rpTf.jpg" target="_blank"><img src="https://imgur.com/dK3rpTf.jpg" alt="Hippodrome" style="width:300px;height:auto;border-radius:8px;"></div>');

//Bellevue / Del Perro / Vespucci
L.marker([-250,-1680], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Cimetière Bellevue</h3><a href="https://imgur.com/k5AM72Z.jpg" target="_blank"><img src="https://imgur.com/k5AM72Z.jpg" alt="Cimetière" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-630,-1830], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Villas Plage / Maisons Vespucci</h3><a href="https://imgur.com/6N2eR4L.jpg" target="_blank"><img src="https://imgur.com/6N2eR4L.jpg" alt="Villas Plage / Maisons Vespucci" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1050,-1590], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Fête Foraine</h3><a href="https://imgur.com/39ocPj9.jpg" target="_blank"><img src="https://imgur.com/39ocPj9.jpg" alt="Fête Foraine" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([300,-2240], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Kortz Center</h3><a href="https://imgur.com/zThnUK5.jpg" target="_blank"><img src="https://imgur.com/zThnUK5.jpg" alt="Kortz Center" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-110,-1300], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Tennis</h3><a href="https://imgur.com/LA1DQMY.jpg" target="_blank"><img src="https://imgur.com/LA1DQMY.jpg" alt="Tennis" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-260,-1050], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Life Invader</h3><a href="https://imgur.com/xxvduKY.jpg" target="_blank"><img src="https://imgur.com/xxvduKY.jpg" alt="Life Invader" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-280,-975], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Rockford Records</h3><a href="https://imgur.com/yvjkCtB.jpg" target="_blank"><img src="https://imgur.com/yvjkCtB.jpg" alt="Akan Records / Rockford Records" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-525,-1090], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Studio Cinéma</h3><a href="https://imgur.com/F6DXlKJ.jpg" target="_blank"><img src="https://imgur.com/F6DXlKJ.jpg" alt="Studio Cinéma" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-680,-1190], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Parking Multicolore</h3><a href="https://imgur.com/oezpGwY.jpg" target="_blank"><img src="https://imgur.com/oezpGwY.jpg" alt="Parking Multicolore" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-760,-900], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Skatepark</h3><a href="https://imgur.com/TwHrPxz.jpg" target="_blank"><img src="https://imgur.com/TwHrPxz.jpg" alt="Skatepark" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-870,-860], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Mausolée Chinois / Sépulture</h3><a href="https://imgur.com/RBF3rMh.jpg" target="_blank"><img src="https://imgur.com/RBF3rMh.jpg" alt="Mausolée Chinois / Sépulture" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-850,-1070], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>PDP Vespucci</h3><a href="https://imgur.com/fu16sTG.jpg" target="_blank"><img src="https://imgur.com/fu16sTG.jpg" alt="PDP Vespucci" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1090,-1010], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Canaux de Vespucci</h3><a href="https://imgur.com/rtwU5Lf.jpg" target="_blank"><img src="https://imgur.com/rtwU5Lf.jpg" alt="Canaux de Vespucci" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-905,-1155], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Burger Shot</h3><a href="https://imgur.com/hGrbgPq.jpg" target="_blank"><img src="https://imgur.com/hGrbgPq.jpg" alt="Burger Shot" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-1055,-1275], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Hôtel V / Hôtel Five</h3><a href="https://imgur.com/VjN7G4z.jpg" target="_blank"><img src="https://imgur.com/VjN7G4z.jpg" alt="Hôtel V / Hôtel Five" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-875,-1250], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Arche</h3><a href="https://imgur.com/IKVokAV.jpg" target="_blank"><img src="https://imgur.com/IKVokAV.jpg" alt="Arche" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-670,-1450], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Motel</h3><a href="https://imgur.com/AbZw0VP.jpg" target="_blank"><img src="https://imgur.com/AbZw0VP.jpg" alt="Motel" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-585,-1545], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Lombank</h3><a href="https://imgur.com/6pM5WBU.jpg" target="_blank"><img src="https://imgur.com/6pM5WBU.jpg" alt="Lombank" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-350,-1450], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Quartier Morningwood</h3><a href="https://imgur.com/iwz03EQ.jpg" target="_blank"><img src="https://imgur.com/iwz03EQ.jpg" alt="Quartier Morningwood" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-225,-770], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Concess Rockford</h3><a href="https://imgur.com/loizznM.jpg" target="_blank"><img src="https://imgur.com/loizznM.jpg" alt="Concess Luxe / Luxury" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-316,-755], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Darnell</h3><a href="https://imgur.com/O9s3sUT.jpg" target="_blank"><img src="https://imgur.com/O9s3sUT.jpg" alt="Concess Luxe / Luxury" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-250,-620], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Bijouterie</h3><a href="https://imgur.com/2KuAJ0V.jpg" target="_blank"><img src="https://imgur.com/2KuAJ0V.jpg" alt="Bijouterie" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-700,-1275], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Rue Piétonne / Rue Marchande</h3><a href="https://imgur.com/kXg7nXF.jpg" target="_blank"><img src="https://imgur.com/kXg7nXF.jpg" alt="Rue Piétonne" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-335,-1970], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Parking Bellevue</h3><a href="https://imgur.com/9EupAfG.jpg" target="_blank"><img src="https://imgur.com/9EupAfG.jpg" alt="Parking Bellevue" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-370,-875], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Backlot</h3><a href="https://imgur.com/3ynfEYP.jpg" target="_blank"><img src="https://imgur.com/3ynfEYP.jpg" alt="Backlot" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([-460,-880], {icon: customIcon("vert-fonce")}).addTo(PosGroup).addTo(DelPerroVespucci).bindPopup('<div style="text-align:center;"><h3>Weazel Plaza</h3><a href="https://imgur.com/cMTlqJM.jpg" target="_blank"><img src="https://imgur.com/cMTlqJM.jpg" alt="Weazel Plaza" style="width:300px;height:auto;border-radius:8px;"></a></div>');


//Secteur Univ
L.marker([50,-1150], {icon: customIcon("vert")}).addTo(PosGroup).addTo(Univ).bindPopup('<div style="text-align:center;"><h3>Golf</h3><a href="https://imgur.com/p5Hdhrp.jpg" target="_blank"><img src="https://imgur.com/p5Hdhrp.jpg" alt="Golf" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([300,-1300], {icon: customIcon("vert")}).addTo(PosGroup).addTo(Univ).bindPopup('<div style="text-align:center;"><h3>Hotel Rose</h3><a href="https://imgur.com/PAehHOE.jpg" target="_blank"><img src="https://imgur.com/PAehHOE.jpg" alt="Hotel Rose" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([270,-1620], {icon: customIcon("vert")}).addTo(PosGroup).addTo(Univ).bindPopup('<div style="text-align:center;"><h3>Police Academy</h3><a href="https://imgur.com/Gpsne3N.jpg" target="_blank"><img src="https://imgur.com/Gpsne3N.jpg" alt="Police Academy" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([140,-1620], {icon: customIcon("vert")}).addTo(PosGroup).addTo(Univ).bindPopup('<div style="text-align:center;"><h3>Gouvernement</h3><a href="https://imgur.com/qyAGn3C.jpg" target="_blank"><img src="https://imgur.com/qyAGn3C.jpg" alt="Gouvernement" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([180,-1550], {icon: customIcon("vert")}).addTo(PosGroup).addTo(Univ).bindPopup('<div style="text-align:center;"><h3>Tribunal</h3><a href="https://imgur.com/urx5SUm.jpg" target="_blank"><img src="https://imgur.com/urx5SUm.jpg" alt="Tribunal" style="width:300px;height:auto;border-radius:8px;"></a></div>');
L.marker([100,-1500], {icon: customIcon("vert")}).addTo(PosGroup).addTo(Univ).bindPopup('<div style="text-align:center;"><h3>Villa Playboy</h3><a href="https://imgur.com/pNT8mui.jpg" target="_blank"><img src="https://imgur.com/pNT8mui.jpg" alt="Villa Playboy" style="width:300px;height:auto;border-radius:8px;"></a></div>');

//Secteur Nord
L.marker([2825,2825], {icon: customIcon("violet")}).addTo(PosGroup).addTo(Nord).bindPopup('<div style="text-align:center;"><h3>Atelis</h3><a href="https://imgur.com/eXcjZJd.jpg" target="_blank"><img src="https://imgur.com/eXcjZJd.jpg" alt="Mine" style="width:300px;height:auto;border-radius:8px;"></a></div>');
